name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore MCHSWebAPI.Tests/MCHSWebAPI.Tests.csproj
    - name: Build
      run: dotnet build MCHSWebAPI.Tests/MCHSWebAPI.Tests.csproj --no-restore
    - name: Test
      run: dotnet test MCHSWebAPI.Tests/MCHSWebAPI.Tests.csproj --no-build --verbosity normal
